/*
    Init script for pgbench.  

    Creates table `dev_text.pgbench` with 
    scale * 10,000 rows.
    
    length(md5()) = 32
    Total length of text is pseudo-random using
    32 * (base_legth + ceil(random() * 25))

    Example usage:
         psql -d bench_test \
            -v scale=100 -v base_length=55 \
            -f init/big_text.sql 

*/


CREATE SCHEMA IF NOT EXISTS dev_text;
DROP TABLE IF EXISTS dev_text.pgbench CASCADE;

CREATE TABLE dev_text.pgbench
(
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    val TEXT NOT NULL
);



INSERT INTO dev_text.pgbench (val)
SELECT repeat(md5(random()::TEXT),
            :base_length + ceil(random() * 25)::INT)
    FROM generate_series(1, (:scale * 10000) ) x
;


ANALYZE dev_text.pgbench;

